included:
  - Sources
  - Tests
excluded:
  - .build
opt_in_rules: [all]
disabled_rules:
  - anonymous_argument_in_multiline_closure
  - async_without_await
  - conditional_returns_on_newline
  - contrasted_opening_brace
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - file_types_order
  - force_try
  - force_unwrapping
  - function_default_parameter_at_end
  - missing_docs
  - no_extension_access_modifier
  - no_grouping_extension
  - one_declaration_per_file
  - prefixed_toplevel_constant
  - sorted_enum_cases
  - sorted_imports
  - switch_case_on_newline
  - unneeded_throws_rethrows
  - unused_parameter
  - variable_shadowing
  - vertical_whitespace_between_cases
line_length:
  warning: 180
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_multiline_strings: true
  ignores_regex_literals: true
file_length:
  ignore_comment_only_lines: true
cyclomatic_complexity:
  ignores_case_statements: true
identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - ^i$
multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true
nesting:
  type_level: 2
number_separator:
  minimum_length: 5
trailing_comma:
  mandatory_comma: true
trailing_closure:
  only_single_muted_parameter: true
type_contents_order:
  order:
    - [case]
    - [type_alias, associated_type]
    - [type_property]
    - [instance_property]
    - [initializer]
    - [deinitializer]
    - [subscript]
    - [other_method]
    - [type_method]
    - [subtype]
